import {
  addLearningEvent,
  addMistake,
  clearMistakes,
  getDailyStats,
  getItemMastery,
  getLearningEvents,
  progressRepository as baseProgressRepository,
  readProgress,
  removeMistake,
  resetProgress,
  saveBossScore,
  updateDailyStats,
  updateItemMastery,
  updateProgress,
  writeProgress,
} from '../utils/storage.js';

export const storageRepository = {
  read: readProgress,
  write: writeProgress,
  update: updateProgress,
  reset: resetProgress,
  addLearningEvent,
  getLearningEvents,
  getItemMastery,
  updateItemMastery,
  getDailyStats,
  updateDailyStats,
  addMistake,
  removeMistake,
  clearMistakes,
  saveBossScore,
};

export {
  addLearningEvent,
  addMistake,
  baseProgressRepository,
  clearMistakes,
  getDailyStats,
  getItemMastery,
  getLearningEvents,
  readProgress,
  removeMistake,
  resetProgress,
  saveBossScore,
  updateDailyStats,
  updateItemMastery,
  updateProgress,
  writeProgress,
};
