export {
  addMistake,
  clearMistakes,
  defaultProgress,
  getProgress,
  markWordHard,
  markWordKnown,
  readProgress,
  removeMistake,
  resetProgress,
  saveBossScore,
  sanitizeProgress,
  saveProgress,
  updateProgress,
  writeProgress,
} from '../utils/storage.js';
